server:
  port: 8300

spring:
  profiles:
    active: dev
  application:
    name: ananops-provider-imc
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  jackson:
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    date-format: yyyy-MM-dd HH:mm:ss
  cache:
    cache-names: mdm-cache
  datasource:
    url: jdbc:mysql://ananops-db-mysql:3306/ananops_pmc?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
